name: Build APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: ArtemSerebrennikov/buildozer-action@v1
        with:
          buildozer_version: latest
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Runamo-APK-File
          path: bin/*.apk
          














